version: '3.8'

services:

  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4JLABS_PLUGINS: '["graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: gds.*
      NEO4J_dbms_security_procedures_allowlist: gds.*
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - neo4j-data:/data
    networks:
      - clear_path_net

  asp-run:
    image: asouthwick1/nycapp:asprun
    container_name: asp-run
    ports:
      - "80:8080"
    env_file: 
      - .env
    networks:
      - clear_path_net

volumes:
  neo4j-data:
    external: true

networks:
  clear_path_net:
    driver: bridge