version: '3.8'

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
      - "3000:80"

  dotnet:
    build:
      context: .
      dockerfile: Dockerfile.dotnet
    ports:
      - "5000:80"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - react
      - dotnet