version: '3.8'

services:
  react-app:
    image: asouthwick1/nycapp:react
    container_name: react-app
    ports:
      - "3000:80"
    networks:
      - clear_path_net

  nginx:
    image: asouthwick1/nycapp:proxy
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - react-app
    networks:
      - clear_path_net

networks:
  clear_path_net: