version: '3.8'

services:

  modeling:
    image: asouthwick1/nycapp:modeling
    container_name: modeling
    ports:
      - "4000:5000"
    networks:
      - clearpath_net

networks:
  clearpath_net:
    external: true
    driver: bridge