version: '3.8'

services:
  webapp:
    image: your-dockerhub-username/your-aspnet-app:latest
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./logs:/app/logs
    restart: no
