version: '3.8'

neo4j:
    image: neo4j
    container_name: neo4j-container
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j-data:/data
    networks:
      - clear_path_net

services:
  asp-run:
    image: asouthwick1/nycapp:asprun
    container_name: asp-run
    ports:
      - "5000:8080"
    depends_on:
      - neo4j
    env_file: 
      - .env
    networks:
      - clear_path_net

  react-app:
    image: asouthwick1/nycapp:react
    container_name: react-app
    ports:
      - "3000:80"
    depends_on:
      - asp-run
    networks:
      - clear_path_net

  nginx:
    image: asouthwick1/nycapp:proxy
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - react-app
      - asp-run
      - neo4j
    networks:
      - clear_path_net

volumes:
  neo4j-data:

networks:
  clear_path_net:
    driver: bridge