version: '3.8'

services:

  neo4j:
    image: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4JLABS_PLUGINS: '["graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: gds.*
      NEO4J_dbms_security_procedures_allowlist: gds.*
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - neo4j-data:/data
    networks:
      - clearpath_net

  modeling:
    image: asouthwick1/nycapp:modeling
    container_name: modeling
    ports:
      - "4000:5000"
    depends_on:
      - neo4j
    networks:
      - clearpath_net

  asp-build:
    image: asouthwick1/nycapp:aspbuild
    container_name: asp-build
    ports:
      - "5001:8080"
    depends_on:
      - neo4j
      - modeling
    networks:
      - clearpath_net

  asp-run:
    image: asouthwick1/nycapp:asprun
    container_name: asp-run
    ports:
      - "5000:8080"
    env_file: 
      - .env
    depends_on:
      - neo4j
      - modeling
    networks:
      - clearpath_net

  react-app:
    image: asouthwick1/nycapp:react
    container_name: react-app
    ports:
      - "3000:80"
    depends_on:
      - asp-run
    networks:
      - clearpath_net

  nginx:
    image: asouthwick1/nycapp:proxy
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - react-app
      - asp-run
    networks:
      - clearpath_net

volumes:
  neo4j-data:
    external: true

networks:
  clear_path_net:
    external: true
    driver: bridge