version: '3.8'

services:
  webapp:
    image: asouthwick1/nycapp:latest
    ports:
      - "8080:80"
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./logs:/app/logs
    restart: "no"
