version: '3.8'

services:
  webapp:
    image: asouthwick1/nycapp:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
    volumes:
      - ./logs:/app/logs
    restart: "no"
