version: '3.8'

services:
  react-app:
    image: asouthwick1/nycapp:react
    container_name: react-app
    ports:
      - "3000:80"
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - react-app
    networks:
      - webnet

networks:
  webnet:
