FROM centos:latest

COPY /model_service .

RUN yum install python3 -y && \
    python3 -m pip install --upgrade pip && \
    python3 -m pip install -r requirements.txt

EXPOSE 5000

ENTRYPOINT ["python3", "./app.py"]