FROM ubuntu:latest

ENV VIRTUAL_ENV=/opt/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY /model_service .

RUN apt-get update && \
    apt-get install -y python3 python3-venv python3-pip && \
    python3 -m venv $VIRTUAL_ENV && \
    $VIRTUAL_ENV/bin/pip install --upgrade pip && \
    $VIRTUAL_ENV/bin/pip install -r requirements.txt

EXPOSE 5000

ENTRYPOINT ["python3", "./app.py"]