# Build stage
FROM python:3.12-slim AS build-stage

WORKDIR /app

COPY model_service/requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# Production stage
FROM python:3.12-slim

WORKDIR /app

COPY --from=build-stage /app /app

EXPOSE 5000
CMD ["gunicorn", "-c", "gunicorn_config.py", "app:app"]