# BUILD
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Restore dotnet packages
COPY aspBuild.csproj .
RUN dotnet restore
# Install curl
RUN apt-get update && apt-get install -y curl

# Publish
COPY . .
RUN dotnet publish -c Release -o /app/out

# RUNTIME
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app/out .

EXPOSE 8080

ENTRYPOINT ["dotnet", "aspBuild.dll"]