# BUILD
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Restore dotnet packages
COPY aspRun.csproj .
RUN dotnet restore
# Publish
COPY . .
RUN dotnet publish -c Release -o /app/out

# RUNTIME
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

ENV WEATHER_KEY=your_actual_api_key

COPY --from=build /app/out .

EXPOSE 8080

ENTRYPOINT ["dotnet", "aspRun.dll"]