# BUILD
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Restore dotnet packages
COPY asp-run.csproj .
RUN dotnet restore
# Publish
COPY . .
RUN dotnet publish -c Release -o /app/out

# RUNTIME
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app/out .

EXPOSE 8080
EXPOSE 80

ENTRYPOINT ["dotnet", "asp-run.dll"]