name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      $(cat /.gitignore/credentials.env | xargs)
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${DOCKER_USERNAME}
        password: ${DOCKER_PASSWORD}
        
    - name: Build Docker image
      run: docker build -t asouthwick1/NewYorkApp:latest .
      
    - name: Push Docker image to Docker Hub
      run: docker push asouthwick1/NewYorkApp:latest