name: main-push

on:
  push:
    branches:
      - mnt

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Docker Image
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: aspRun
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        working-directory: ./backend/aspRun
        run: |
          docker build -t $DOCKER_USERNAME/nycapp:asprun -f Dockerfile.aspRun .
          echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/nycapp:asprun